/** JeevanSetu local API — demo only. Do not use with real biometric data. */
import http from 'node:http';
import {createHmac, randomUUID, scryptSync, timingSafeEqual} from 'node:crypto';
import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=dirname(fileURLToPath(import.meta.url)), storePath=join(root,'data.json'), secret='jeevansetu-local-demo-only';
const seed={users:[{id:'u-citizen',name:'Shivam Verma',email:'citizen@jeevansetu.local',role:'citizen',password:hash('demo1234')},{id:'u-police',name:'Inspector Meera Singh',email:'police@jeevansetu.local',role:'police',password:hash('demo1234')}],incidents:[{id:'JS-2026-00001',reporterId:'u-citizen',location:'Yamuna River, ITO Bridge',latitude:28.6315,longitude:77.2465,waterBody:'River',description:'Suspected person observed near the riverbank.',reportedAt:'2026-08-19T11:42:00.000Z',status:'awaiting_response',responseStatus:'pending',escalationStatus:'monitoring',priority:'high',stage:'Police alerted'}],missingPersons:[{id:'MP-2026-00418',name:'Rohan Verma',age:34,gender:'Male',lastSeenLocation:'Noida, Sector 62',lastSeenDate:'2026-08-16',clothing:'Blue checked shirt',identificationMarks:'Small scar near left eyebrow',status:'active'}],bodies:[{id:'UB-2026-00001',incidentId:'JS-2026-00001',estimatedAge:35,gender:'Male',clothing:'Blue checked shirt',identificationMarks:'Small scar near left eyebrow',recoveryLocation:'Hindon Canal',recoveryDate:'2026-08-19',status:'possible_match_found'}],alerts:[],rescueRequests:[]};
function hash(v){return scryptSync(v,'jeevansetu-salt',32).toString('hex')}function db(){if(!existsSync(storePath)){mkdirSync(root,{recursive:true});writeFileSync(storePath,JSON.stringify(seed,null,2))}return JSON.parse(readFileSync(storePath,'utf8'))}function save(d){writeFileSync(storePath,JSON.stringify(d,null,2))}function token(u){return Buffer.from(JSON.stringify({sub:u.id,role:u.role,exp:Date.now()+86400000})).toString('base64url')+'.'+createHmac('sha256',secret).update(u.id).digest('base64url')}function user(req,d){let t=(req.headers.authorization||'').replace('Bearer ','');if(!t)return null;let [raw,sig]=t.split('.');try{let x=JSON.parse(Buffer.from(raw,'base64url'));if(sig!==createHmac('sha256',secret).update(x.sub).digest('base64url')||x.exp<Date.now())return null;return d.users.find(u=>u.id===x.sub)||null}catch{return null}}
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, PATCH, OPTIONS'});res.end(JSON.stringify(data))}async function body(req){let s='';for await(const c of req)s+=c;if(!s)return {};try{return JSON.parse(s)}catch{throw Error('Invalid JSON')}}function next(d,prefix,list){let y=new Date().getFullYear(),n=list.length+1;return `${prefix}-${y}-${String(n).padStart(5,'0')}`}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return send(res,204,{});let url=new URL(req.url,'http://localhost:4000'),path=url.pathname,d=db();try{if(req.method==='GET'&&path==='/api/health')return send(res,200,{ok:true,service:'JeevanSetu local API'});
if(req.method==='POST'&&path==='/api/auth/login'){let b=await body(req),u=d.users.find(x=>x.email===b.email);if(!u||!timingSafeEqual(Buffer.from(u.password),Buffer.from(hash(b.password||''))))return send(res,401,{error:'Invalid email or password'});return send(res,200,{token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
if(req.method==='POST'&&path==='/api/auth/register'){let b=await body(req);if(!b.name||!b.email||!b.password)return send(res,400,{error:'Name, email and password are required'});if(d.users.some(u=>u.email===b.email))return send(res,409,{error:'Email already registered'});let u={id:randomUUID(),name:b.name,email:b.email,role:'citizen',password:hash(b.password)};d.users.push(u);save(d);return send(res,201,{token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
let u=user(req,d);if(!u)return send(res,401,{error:'Authentication required'});
if(req.method==='GET'&&path==='/api/incidents')return send(res,200,{items:u.role==='citizen'?d.incidents.filter(x=>x.reporterId===u.id):d.incidents});
if(req.method==='POST'&&path==='/api/incidents'){let b=await body(req);if(!b.location||!b.description)return send(res,400,{error:'Location and description are required'});let item={id:next(d,'JS',d.incidents),reporterId:u.id,location:b.location,latitude:b.latitude||null,longitude:b.longitude||null,waterBody:b.waterBody||'Not specified',description:b.description,reportedAt:new Date().toISOString(),status:'awaiting_response',responseStatus:'pending',escalationStatus:'monitoring',priority:b.priority||'high',stage:'Police alerted',evidence:b.evidence||[]};d.incidents.unshift(item);save(d);return send(res,201,{item,message:'Report submitted successfully'})}
let incident=path.match(/^\/api\/incidents\/(JS-\d{4}-\d+)$/);if(req.method==='GET'&&incident){let i=d.incidents.find(x=>x.id===incident[1]);return i?send(res,200,{item:i,timeline:timeline(i)}):send(res,404,{error:'Case not found'})}if(req.method==='PATCH'&&incident){if(!['police','control_room','admin'].includes(u.role))return send(res,403,{error:'Authorized role required'});let i=d.incidents.find(x=>x.id===incident[1]),b=await body(req);if(!i)return send(res,404,{error:'Case not found'});Object.assign(i,allowed(b,['status','responseStatus','escalationStatus','priority','stage']));save(d);return send(res,200,{item:i})}
if(req.method==='GET'&&path==='/api/escalations')return send(res,200,{items:d.incidents.filter(i=>i.escalationStatus==='escalated'||i.responseStatus==='pending').map(i=>({...i,threshold:'Configurable by authority',action:i.escalationStatus==='escalated'?'Control room action required':'Monitoring response'}))});
if(req.method==='GET'&&path==='/api/missing-persons')return send(res,200,{items:d.missingPersons});if(req.method==='POST'&&path==='/api/missing-persons'){let b=await body(req);if(!b.name||!b.age||!b.gender)return send(res,400,{error:'Name, age and gender are required'});let x={id:next(d,'MP',d.missingPersons),...b,status:'active',createdAt:new Date().toISOString()};d.missingPersons.unshift(x);save(d);return send(res,201,{item:x})}
if(req.method==='GET'&&path==='/api/bodies')return send(res,200,{items:d.bodies});if(req.method==='POST'&&path==='/api/bodies'){if(!['police','admin'].includes(u.role))return send(res,403,{error:'Authorized role required'});let b=await body(req),x={id:next(d,'UB',d.bodies),...b,status:'identification_pending',createdAt:new Date().toISOString()};d.bodies.unshift(x);save(d);return send(res,201,{item:x})}
let m=path.match(/^\/api\/identification\/matches\/(UB-\d{4}-\d+)$/);if(req.method==='GET'&&m){let b=d.bodies.find(x=>x.id===m[1]);if(!b)return send(res,404,{error:'Body record not found'});let matches=d.missingPersons.map(p=>({missingPerson:p,similarity:similarity(b,p),decision:'Possible Match — Requires Official Verification',modelState:['Image uploaded','Face quality checked','Matching complete']})).sort((a,b)=>b.similarity-a.similarity);return send(res,200,{body:b,matches,notice:'AI-assisted results are not identity confirmation and require police/forensic verification.'})}
if(req.method==='GET'&&path==='/api/rescue-requests')return send(res,200,{items:d.rescueRequests});if(req.method==='POST'&&path==='/api/rescue-requests'){if(!['police','admin'].includes(u.role))return send(res,403,{error:'Authorized role required'});let b=await body(req),x={id:randomUUID(),...b,status:'requested',createdAt:new Date().toISOString()};d.rescueRequests.unshift(x);save(d);return send(res,201,{item:x})}
if(req.method==='GET'&&path==='/api/alerts')return send(res,200,{items:d.alerts});if(req.method==='POST'&&path==='/api/alerts'){if(!['police','control_room','admin'].includes(u.role))return send(res,403,{error:'Authorized role required'});let b=await body(req),x={id:randomUUID(),...b,status:'authorized',createdAt:new Date().toISOString(),createdBy:u.id};d.alerts.unshift(x);save(d);return send(res,201,{item:x})}
return send(res,404,{error:'Route not found'})}catch(e){return send(res,400,{error:e.message||'Request failed'})}});
function allowed(o,keys){return Object.fromEntries(keys.filter(k=>o[k]!==undefined).map(k=>[k,o[k]]))}function timeline(i){return ['Report submitted','Police alerted','Police acknowledged','Police verification','Rescue requested','Rescue team assigned','Recovery operation','Body recovered','Identification process','Official verification','Case resolved'].map((x,n)=>({label:x,current:x===i.stage,complete:n<2}))}function similarity(b,p){let score=55;if((b.gender||'').toLowerCase()===(p.gender||'').toLowerCase())score+=11;if(Math.abs((b.estimatedAge||0)-(p.age||0))<=4)score+=13;if(b.clothing&&p.clothing&&b.clothing.toLowerCase()===p.clothing.toLowerCase())score+=12;if(b.identificationMarks&&p.identificationMarks&&b.identificationMarks.toLowerCase()===p.identificationMarks.toLowerCase())score+=10;return Math.min(score,98)}
server.listen(4000,()=>console.log('JeevanSetu API running at http://localhost:4000'));
